baseURL = "https://trebaud.github.io/"
languageCode = "en-us"
paginate = 5
tags = ["development", "python", "neovim"]
theme = "hello-friend-trebaud"
title = "Yet Another Random Memoir"

[params]
dateform        = "Jan 2, 2006"
dateformShort   = "Jan 2"
dateformNum     = "2006-01-02"
dateformNumTime = "2006-01-02 15:04"

description = "My blog"
keywords = ""
images = [""]

homeSubtitle = "A collection of loosely coupled ramblings about tech, coding and life." 

disableReadOtherPosts = false
enableThemeToggle = true
enableSharingButtons = true
enableComments = true
missingContentMessage = "??"

[params.utterances]
owner = "trebaud"
repo = "trebaud.github.io"

[params.logo]
logoMark     = ">"
logoText     = "$ cd /home/"
logoHomeLink = "/"

[[params.social]]
name = "github"
url = "https://github.com/trebaud"

[[params.social]]
name = "linkedin"
url = "https://www.linkedin.com/in/thomas-rebaud-8017a168/"

[taxonomies]
tag = "tags"
category = "categories"

[menu]
    [[menu.main]]
    name = "📝 All posts"
    url = "/posts"
    weight = 2
    
    [[menu.main]]
    name = "👨‍💻 Whoami"
    url = "/whoami"
    weight = 3
    
    [[menu.main]]
    name = "🔍 Tags"
    url = "/tags"
    weight = 4
    
    [[menu.main]]
    name = "🎸"
    url = "/neck-visualizer"
    weight = 5
