baseURL = "https://trebaud.github.io/"
languageCode = "en-us"
paginate = 5
tags = ["development", "python", "neovim"]
theme = "hugo-ink"
title = "Yet another tech blog"

pygmentsCodeFences = true
pygmentsStyle = "colorful"

[params]
avatar = "https://avatars2.githubusercontent.com/u/8050949?s=400&v=4" 
disableDisqusTypes = ["page"] 
featherIconsCDN = true 
mode = "auto" # "dark" or "auto"
subtitle = "A collection of loosely coupled ramblings about tech, coding and life." 

# Nav.
[[menu.main]]
name = "🏠 Home"
url = "/"
weight = 1

[[menu.main]]
name = "📝 All posts"
url = "/posts"
weight = 2

[[menu.main]]
name = "👨‍💻 About"
url = "/about"
weight = 3

[[menu.main]]
name = "🔍 Tags"
url = "/tags"
weight = 4

[[menu.main]]
name = "🎸"
url = "/neck-visualizer"
weight = 4

[[params.social]]
icon = "github"
name = "Github"
url = "https://github.com/trebaud"

[[params.social]]
icon = "linkedin"
name = "Linkedin"
url = "https://www.linkedin.com/in/thomas-rebaud-8017a168/"

[taxonomies]
tag = "tags"
